export const getEndpointsList = () => Array.from([
  ['', 'Financial Times REST API'],
  ['https://markets.ft.com/research/webservices/securities/v1/dividends', 'Dividends'],
  ['https://markets.ft.com/research/webservices/securities/v1/quotes', 'Quotes'],
  ['https://markets.ft.com/research/webservices/securities/v1/indices', 'Indices'],
  ['https://markets.ft.com/research/webservices/securities/v1/commodities', 'Commodities'],
  ['https://markets.ft.com/research/webservices/securities/v1/currencies', 'Currencies'],
  ['https://markets.ft.com/research/webservices/securities/v1/bonds', 'Bonds'],
  ['https://markets.ft.com/research/webservices/securities/v1/etfs', 'ETFs'],
  ['https://markets.ft.com/research/webservices/securities/v1/funds', 'Funds'],
  ['https://markets.ft.com/research/webservices/securities/v1/companies', 'Companies'],
  ['https://markets.ft.com/research/webservices/securities/v1/markets', 'Markets'],
  ['https://markets.ft.com/research/webservices/securities/v1/sector', 'Sectors'],
  ['https://markets.ft.com/research/webservices/securities/v1/countries', 'Countries'],
  ['https://markets.ft.com/research/webservices/securities/v1/regions', 'Regions'],
  ['https://markets.ft.com/research/webservices/securities/v1/industries', 'Industries'],
])

export const getParamsByEndpoint = (endpoint) => ({
  'Financial Times REST API': [],
  'Dividends': ['symbols', 'source'],
  'Quotes': [],
  'Indices': [],
  'Commodities': [],
  'Currencies': [],
  'Bonds': [],
  'ETFs': [],
  'Funds': [],
  'Companies': [],
  'Markets': [],
  'Sectors': [],
  'Countries': [],
  'Regions': [],
  'Industries': [],
})[endpoint]
